version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - bot_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - api
    networks:
      - bot_network

  api:
    build:
      context: ./web/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - bot_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot_network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot_network

volumes:
  postgres_data:
  redis_data:

networks:
  bot_network:
    driver: bridge 