version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - bot_network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.50'
        reservations:
          memory: 64M
          cpus: '0.25'
    mem_swappiness: 0
    oom_kill_disable: true

  web:
    build:
      context: ./web/client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:3000"
    env_file: .env
    depends_on:
      - api
      - redis
      - db
    networks:
      - bot_network
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    mem_swappiness: 0
    oom_kill_disable: true

  api:
    build:
      context: ./web/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - bot_network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.50'
        reservations:
          memory: 64M
          cpus: '0.25'
    mem_swappiness: 0
    oom_kill_disable: true

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # PostgreSQLのメモリ設定
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 384MB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bot_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.75'
        reservations:
          memory: 128M
          cpus: '0.25'
    mem_swappiness: 0
    oom_kill_disable: true
    command: postgres -c shared_buffers=64MB -c effective_cache_size=192MB -c work_mem=8MB -c maintenance_work_mem=16MB -c max_connections=50

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru --save "" --appendonly no
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot_network
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'
        reservations:
          memory: 32M
          cpus: '0.10'
    mem_swappiness: 0
    oom_kill_disable: true

volumes:
  postgres_data:
  redis_data:

networks:
  bot_network:
    driver: bridge 